### PR TITLE
More various changes

### PR DESCRIPTION
**Pull request by 1011025m**
unified font imports, spotify icons should pull from repository directly via jsdelivr

### CODE REVIEW

**Comment by 1011025m** [comment]
lmao i think this made the infinite loading

**Comment by 1011025m** [comment]
Most of the variables are not used, do you want to remove them?

I also suggest that you just remove unused rules, rather than commenting them out.

**Comment by 1011025m** [comment]
This is quite a big PR - if you can, please check and see if there are any breaking changes since I cannot catch them all.
so much stuff that i forgor i shouldve made a new branch for a new pr bruh

**Comment by JunkiEDM** [comment]
manually merged; unused variables are there to try and prevent 1% of the many many issues that will come once the upcoming soundcloud ui overhaul gets released

**Comment by 1011025m** [comment]
Is this an intended change? My intention for this was turning the background to have a lighter shade of black when the browser does not support backdrop-filter, but it's still being transparent.

image

**Pull request closed without merging**
